### ISSUE TITLE
add ip address and ip address location to link clicks section

### ISSUE THREAD

**Issue by steven4354** [steven4354/email.dev#59]
lets track the ip address of the link clicks and the location from the link clicks e.g. san francisco, california

https://capture.dropbox.com/GYPPIPJgrIcWK5KK

i think some of the link clicks aren't real, and just buy the email client so this info will help us better figure out if they are real link clicks or fake

**Comment by mundia416** [comment]
@steven4354 tracking userAgent seems to be more effective, what are your thoughts?

Added the fact that in order to get the location requires passing the IP address to an external API because the location isn't readily available in an express route request

**Comment by mundia416** [comment]
https://github.com/steven4354/email.dev/pull/62 added tracking of user agent to identify automated link clicks
