### ISSUE TITLE
user agent empty for new clicks

### ISSUE THREAD

**Issue by steven4354** [steven4354/email.dev#65]
https://capture.dropbox.com/p3xqz8EV4nRdxfuW

**Comment by steven4354** [comment]
![Google Chrome - emaildev vercel app-campaigns-fc03f205-9eae-4044-96ad-477efa0a6e3f 2023-06-12 at 1 33 52 PM](https://github.com/steven4354/email.dev/assets/28765991/23ae9732-9692-4338-9aa5-27ab7c40a3db)

**Comment by mundia416** [comment]
Fixed this, issue was that the database changes were done to a branch of the main database and not done to the main branch after the merge
